### ISSUE TITLE
error when starting dev server: TypeError: vitePluginCssModules is not a function

### ISSUE THREAD

**Issue by thisVioletHydra** [zebing/vite-plugin-css-modules#6]
subz

**Comment by zebing** [comment]
@thisVioletHydra This may help you https://github.com/zebing/vite-plugin-css-modules/blob/master/examples/vite3/csr/vite.config.js

**Comment by zebing** [comment]
@thisVioletHydra  You can refer to examples

**Comment by thisVioletHydra** [comment]
I'm on vacation right now, I'll check later
